export default {
  box_gallery: document.querySelector(".box-gallery"),
  // source_mobile_man: document.querySelector(".source-mobile-man"),
  // source_tablet_man: document.querySelector(".source-tablet-man"),
  // source_mobile_woman: document.querySelector(".source-mobile-woman"),
  // source_tablet_woman: document.querySelector(".source-tablet-woman"),
  img_large_man: document.querySelector(".img-large-man"),
  img_large_woman: document.querySelector(".img-large-woman"),
  item_man_small: document.querySelectorAll(".man-small-photo"),
  item_woman_small: document.querySelectorAll(".woman-small-photo"),

  form: document.querySelector(".form"),
  label_name: document.querySelector(".label-name"),
  label_tel: document.querySelector(".label-tel"),
  box_message: document.querySelector(".box-message"),
  name_box_message: document.querySelector(".name-box-message"),
  name_message: document.querySelector(".name-message"),
  tel_box_message: document.querySelector(".tel-box-message"),
  tel_message: document.querySelector(".tel-message"),
  input_name: document.querySelector(".input-name"),
  input_tel: document.querySelector(".input-tel"),
  submit_btn: document.querySelector(".submit-btn"),
  submit_message_success: document.querySelector(".submit-message-success"),
  submit_message_error: document.querySelector(".submit-message-error"),
};
